import CARD_HEARTS_1 from '../assets/cards/card-hearts-1.png';
import CARD_HEARTS_2 from '../assets/cards/card-hearts-2.png';
import CARD_HEARTS_3 from '../assets/cards/card-hearts-3.png';
import CARD_HEARTS_4 from '../assets/cards/card-hearts-4.png';
import CARD_HEARTS_5 from '../assets/cards/card-hearts-5.png';
import CARD_HEARTS_6 from '../assets/cards/card-hearts-6.png';
import CARD_HEARTS_7 from '../assets/cards/card-hearts-7.png';
import CARD_HEARTS_8 from '../assets/cards/card-hearts-8.png';
import CARD_HEARTS_9 from '../assets/cards/card-hearts-9.png';
import CARD_HEARTS_10 from '../assets/cards/card-hearts-10.png';
import CARD_HEARTS_11 from '../assets/cards/card-hearts-11.png';
import CARD_HEARTS_12 from '../assets/cards/card-hearts-12.png';
import CARD_HEARTS_13 from '../assets/cards/card-hearts-13.png';
import CARD_CLUBS_1 from '../assets/cards/card-clubs-1.png';
import CARD_CLUBS_2 from '../assets/cards/card-clubs-2.png';
import CARD_CLUBS_3 from '../assets/cards/card-clubs-3.png';
import CARD_CLUBS_4 from '../assets/cards/card-clubs-4.png';
import CARD_CLUBS_5 from '../assets/cards/card-clubs-5.png';
import CARD_CLUBS_6 from '../assets/cards/card-clubs-6.png';
import CARD_CLUBS_7 from '../assets/cards/card-clubs-7.png';
import CARD_CLUBS_8 from '../assets/cards/card-clubs-8.png';
import CARD_CLUBS_9 from '../assets/cards/card-clubs-9.png';
import CARD_CLUBS_10 from '../assets/cards/card-clubs-10.png';
import CARD_CLUBS_11 from '../assets/cards/card-clubs-11.png';
import CARD_CLUBS_12 from '../assets/cards/card-clubs-12.png';
import CARD_CLUBS_13 from '../assets/cards/card-clubs-13.png';
import CARD_DIAMONDS_1 from '../assets/cards/card-diamonds-1.png';
import CARD_DIAMONDS_2 from '../assets/cards/card-diamonds-2.png';
import CARD_DIAMONDS_3 from '../assets/cards/card-diamonds-3.png';
import CARD_DIAMONDS_4 from '../assets/cards/card-diamonds-4.png';
import CARD_DIAMONDS_5 from '../assets/cards/card-diamonds-5.png';
import CARD_DIAMONDS_6 from '../assets/cards/card-diamonds-6.png';
import CARD_DIAMONDS_7 from '../assets/cards/card-diamonds-7.png';
import CARD_DIAMONDS_8 from '../assets/cards/card-diamonds-8.png';
import CARD_DIAMONDS_9 from '../assets/cards/card-diamonds-9.png';
import CARD_DIAMONDS_10 from '../assets/cards/card-diamonds-10.png';
import CARD_DIAMONDS_11 from '../assets/cards/card-diamonds-11.png';
import CARD_DIAMONDS_12 from '../assets/cards/card-diamonds-12.png';
import CARD_DIAMONDS_13 from '../assets/cards/card-diamonds-13.png';
import CARD_SPADES_1 from '../assets/cards/card-spades-1.png';
import CARD_SPADES_2 from '../assets/cards/card-spades-2.png';
import CARD_SPADES_3 from '../assets/cards/card-spades-3.png';
import CARD_SPADES_4 from '../assets/cards/card-spades-4.png';
import CARD_SPADES_5 from '../assets/cards/card-spades-5.png';
import CARD_SPADES_6 from '../assets/cards/card-spades-6.png';
import CARD_SPADES_7 from '../assets/cards/card-spades-7.png';
import CARD_SPADES_8 from '../assets/cards/card-spades-8.png';
import CARD_SPADES_9 from '../assets/cards/card-spades-9.png';
import CARD_SPADES_10 from '../assets/cards/card-spades-10.png';
import CARD_SPADES_11 from '../assets/cards/card-spades-11.png';
import CARD_SPADES_12 from '../assets/cards/card-spades-12.png';
import CARD_SPADES_13 from '../assets/cards/card-spades-13.png';


export const cardShapes = [
    {shape: "hearts-1", object: CARD_HEARTS_1},
    {shape: "hearts-2", object: CARD_HEARTS_2},
    {shape: "hearts-3", object: CARD_HEARTS_3},
    {shape: "hearts-4", object: CARD_HEARTS_4},
    {shape: "hearts-5", object: CARD_HEARTS_5},
    {shape: "hearts-6", object: CARD_HEARTS_6},
    {shape: "hearts-7", object: CARD_HEARTS_7},
    {shape: "hearts-8", object: CARD_HEARTS_8},
    {shape: "hearts-9", object: CARD_HEARTS_9},
    {shape: "hearts-10", object: CARD_HEARTS_10},
    {shape: "hearts-11", object: CARD_HEARTS_11},
    {shape: "hearts-12", object: CARD_HEARTS_12},
    {shape: "hearts-13", object: CARD_HEARTS_13},
    {shape: "clubs-1", object: CARD_CLUBS_1},
    {shape: "clubs-2", object: CARD_CLUBS_2},
    {shape: "clubs-3", object: CARD_CLUBS_3},
    {shape: "clubs-4", object: CARD_CLUBS_4},
    {shape: "clubs-5", object: CARD_CLUBS_5},
    {shape: "clubs-6", object: CARD_CLUBS_6},
    {shape: "clubs-7", object: CARD_CLUBS_7},
    {shape: "clubs-8", object: CARD_CLUBS_8},
    {shape: "clubs-9", object: CARD_CLUBS_9},
    {shape: "clubs-10", object: CARD_CLUBS_10},
    {shape: "clubs-11", object: CARD_CLUBS_11},
    {shape: "clubs-12", object: CARD_CLUBS_12},
    {shape: "clubs-13", object: CARD_CLUBS_13},
    {shape: "diamonds-1", object: CARD_DIAMONDS_1},
    {shape: "diamonds-2", object: CARD_DIAMONDS_2},
    {shape: "diamonds-3", object: CARD_DIAMONDS_3},
    {shape: "diamonds-4", object: CARD_DIAMONDS_4},
    {shape: "diamonds-5", object: CARD_DIAMONDS_5},
    {shape: "diamonds-6", object: CARD_DIAMONDS_6},
    {shape: "diamonds-7", object: CARD_DIAMONDS_7},
    {shape: "diamonds-8", object: CARD_DIAMONDS_8},
    {shape: "diamonds-9", object: CARD_DIAMONDS_9},
    {shape: "diamonds-10", object: CARD_DIAMONDS_10},
    {shape: "diamonds-11", object: CARD_DIAMONDS_11},
    {shape: "diamonds-12", object: CARD_DIAMONDS_12},
    {shape: "diamonds-13", object: CARD_DIAMONDS_13},
    {shape: "spades-1", object: CARD_SPADES_1},
    {shape: "spades-2", object: CARD_SPADES_2},
    {shape: "spades-3", object: CARD_SPADES_3},
    {shape: "spades-4", object: CARD_SPADES_4},
    {shape: "spades-5", object: CARD_SPADES_5},
    {shape: "spades-6", object: CARD_SPADES_6},
    {shape: "spades-7", object: CARD_SPADES_7},
    {shape: "spades-8", object: CARD_SPADES_8},
    {shape: "spades-9", object: CARD_SPADES_9},
    {shape: "spades-10", object: CARD_SPADES_10},
    {shape: "spades-11", object: CARD_SPADES_11},
    {shape: "spades-12", object: CARD_SPADES_12},
    {shape: "spades-13", object: CARD_SPADES_13},
];